plugins/search/eventsearch.php
Fixing language load for JEvents main search plugin:
https://www.jevents.net/forum/viewtopic.php?f=23&t=27103&p=143393#p143393
=> Fixing language load

component/site/libraries/dbmodel.php
I think having a method for calling custom fields would be good and also adding them to the admin view (in case user needs an override).
=> Adding Custom fields to admin view

component/admin/config.xml, component/site/assets/js/editicalJQ.js, component/site/language/en-GB.com_jevents.ini
Added a few language strings for GWE JSON.
=> Added additional redirect after event of Manage Events

component/admin/libraries/version.php, component/admin/views/icalevent/tmpl/edit16.php, component/admin/views/icalevent/tmpl/edit16_datetime.php, component/admin/views/icalevent/tmpl/edit16_keep.php, component/admin/views/icalevent/tmpl/edit16_prejform.php, component/manifest.xml, component/site/libraries/dbmodel.php, install.php, libraries/googl/googl.xml, modules/mod_jevents_cal/mod_jevents_cal.xml, modules/mod_jevents_custom/mod_jevents_custom.xml, modules/mod_jevents_filter/mod_jevents_filter.xml, modules/mod_jevents_latest/mod_jevents_latest.xml, modules/mod_jevents_legend/mod_jevents_legend.xml, modules/mod_jevents_switchview/mod_jevents_switchview.xml, pkg_jevents.xml, plugins/finder/jevents/jevents.xml, plugins/jevents/jevents.xml, plugins/search/eventsearch.xml
Since JEvents 3.2.14 the edit16 files were removed from icalevent, causing event repeat editing to fallover.
=> JEvents 3.2.21 - Add missing icalevent files

component/admin/controllers/cpanel.php, component/admin/controllers/defaults.php, component/admin/controllers/icalevent.php, component/admin/controllers/icalrepeat.php, component/admin/controllers/icals.php, component/admin/controllers/params.php, component/admin/jevents.php, component/admin/views/cpanel/view.html.php, component/install.php, component/site/jevents.php, component/site/libraries/dbmodel.php, component/site/libraries/helper.php, component/site/libraries/iCalEvent.php, component/site/libraries/iCalICSFile.php, component/site/libraries/jicaleventdb.php, install.php
=> Deprecated class query() updated to execute()

plugins/gwejson/gwejson.php
Allowing GweJSON to search files in libraries too.
=> Adding libraries to gwejson search paths

CHANGELOG.md, component/site/views/default/helpers/defaultexportgoogle.php
…al://, fixes invalid email address issue when adding to google calendar.
=> Updated the google export to support http and https replacing to webcal://, fixes invalid email address issue when adding to google calendar.

component/admin/assets/js/columns.js, component/admin/controllers/icalrepeat.php, component/admin/libraries/version.php, component/admin/views/icalrepeat/tmpl/overview.php, component/manifest.xml, install.php, libraries/googl/googl.xml, libraries/j25legacy/j25legacy.xml, libraries/jevbootstrap/jevbootstrap.xml, libraries/jevmodal/jevmodal.xml, libraries/jevtypeahead/jevtypeahead.xml, modules/mod_jevents_cal/mod_jevents_cal.xml, modules/mod_jevents_custom/mod_jevents_custom.xml, modules/mod_jevents_filter/mod_jevents_filter.xml, modules/mod_jevents_latest/mod_jevents_latest.xml, modules/mod_jevents_legend/mod_jevents_legend.xml, modules/mod_jevents_switchview/mod_jevents_switchview.xml, pkg_jevents.xml, plugins/finder/jevents/jevents.xml, plugins/gwejson/gwejson.xml, plugins/installer/jeventsinstaller.xml, plugins/jevents/jevents.xml, plugins/search/eventsearch.xml
Fix for column selection in list menu item
Fir for deleting first repeat of repeats when repeat id = event id
=> JEvents 3.4.21

component/admin/config.xml, component/admin/jevents.php, component/admin/libraries/config.php, component/site/jevents.php, component/site/libraries/datamodel.php, component/site/views/cat/tmpl/listevents.xml, component/site/views/crawler/tmpl/listevents.xml, component/site/views/list/tmpl/events.xml, component/site/views/range/tmpl/listevents.xml, component/site/views/year/tmpl/listevents.xml
Added Global option and set as default for show all repeats option in Menu items
Merge remote-tracking branch 'upstream/jQuery' into jQuery-J3.7
Conflicts:
component/site/language/en-GB.com_jevents.ini
=> Added Global option and set as default for show all repeats option in Menu items

CHANGELOG.md, component/admin/fields/jeveventpublished.php, component/admin/views/icalevent/view.html.php, component/site/libraries/helper.php
By default users who could publish their own events were not given the state dropdown. This fixes that when using Joomla! ACL.
Plus updated Changelog.
=> Publish State Improvement and Changelog update

component/site/libraries/helper.php
They have broken behavior.calendar and that has broken our date pickers. This PR adds necessary css and js to make them work again.
=> Calendar behavior is deprecated and broken in 3.7

component/admin/controllers/icalevent.php, component/admin/libraries/version.php, component/manifest.xml, install.php, libraries/googl/googl.xml, libraries/j25legacy/j25legacy.xml, libraries/jevbootstrap/jevbootstrap.xml, libraries/jevmodal/jevmodal.xml, libraries/jevtypeahead/jevtypeahead.xml, modules/mod_jevents_cal/mod_jevents_cal.xml, modules/mod_jevents_custom/mod_jevents_custom.xml, modules/mod_jevents_filter/mod_jevents_filter.xml, modules/mod_jevents_latest/mod_jevents_latest.xml, modules/mod_jevents_legend/mod_jevents_legend.xml, modules/mod_jevents_switchview/mod_jevents_switchview.xml, pkg_jevents.xml, plugins/finder/jevents/jevents.xml, plugins/gwejson/gwejson.xml, plugins/installer/jeventsinstaller.xml, plugins/jevents/jevents.xml, plugins/search/eventsearch.xml
JEvents V3.4.38
To be re-addressed in Joomla! 3.7.1.
=> JEvents v3.4.38

component/site/libraries/iCalImport.php, component/site/views/list/tmpl/events.xml
In the list of events menu item we get a 500 Error - Extension attribute not specified. This resolves that.
=> Fixed 500 notice of extension attribute not specified.

plugins/finder/jevents/jevents.php
Smart Search should only find published events.
=> Added where clause to smart search plugin to only find published events.

component/admin/libraries/saveIcalEvent.php
https://www.jevents.net/discussions/publishing-other-users-events#reply-192479
=> Allow notifications for event created in backend

component/admin/controllers/icalrepeat.php, plugins/finder/jevents/jevents.php
Updated Smart Search Plugin to not index unpublished event in getListQuery.
=> Added filtering to iCalRepeat to be same as iCalEvent

component/site/libraries/datamodel.php, component/site/libraries/dbmodel.php, component/site/libraries/helper.php, component/site/views/alternative/month/tmpl/calendar_body.php, component/site/views/alternative/month/tmpl/calendar_bodydiv.php, component/site/views/default/month/tmpl/calendar_body.php, component/site/views/ext/month/tmpl/calendar_body.php
ext month file is the same change as alternative. Just copy/paste so it reformatted the code.
=> PHP 7.2 improvements for the core

component/site/libraries/dbmodel.php
Fix for accesible category list array(-1) all the time
=> Version 3.4.44

CHANGELOG.md, component/site/assets/css/eventsadmin.css, component/site/libraries/helper.php, component/site/views/default/helpers/defaultloadedfromtemplate.php
=> List of events should show full repeat summary

component/site/assets/css/eventsadmin.css, component/site/assets/js/editpopupJQ.js, component/site/views/default/helpers/defaulteventmanagementbutton.php
Drops native bootstrap data modals and uses our JS to work when conflicts occur. 
Adds ID based modal window.
=> Modal quick hide/close for event manage dialog fix

component/admin/views/icals/tmpl/edit.php, component/site/libraries/jeventshtml.php
To replicate, try creating a calendar when JEvents only has 1 category and multi-category support enabled.
=> More Category input fixes

component/media/css/bootstrap.css
The template should handle these.
=> Removed classes we shouldn't be setting.

component/site/views/flat/assets/css/events_css.css
=> Removed Missing Images css styles left from theme it was copied from.

component/site/controllers/icalevent.php, component/site/controllers/icalrepeat.php
* Trigger onBeforeLoadView event to inject View Classes for Event Details
* Disable caching when pdf format (needed for PhocaPDF plugin)
=> Trigger to allow injecting view classes

component/site/assets/js/editpopupJQ.js, component/site/assets/js/jQnc.js, component/site/libraries/bootstrap.php, component/site/libraries/csvLine.php, libraries/jevbootstrap/bootstrap.php, libraries/jevmodal/media/js/jevmodal.js
Set Published State Properly via import, check timezone exists before trying to set it, else use gotten timezone.
=> Improve CSV Importing

component/admin/language/en-GB.com_jevents.ini, component/admin/views/icalevent/tmpl/overview.php, component/site/views/default/list/tmpl/events_body.php, component/site/views/list/tmpl/events.xml, component/site/views/modlatest/view.feed.php
list of events view for each row.
=> Add config option to allow background color to be set for

component/site/libraries/dbmodel.php, component/site/libraries/iCalImport.php, modules/mod_jevents_latest/tmpl/default/latest.php
ref:
https://www.jevents.net/discussions/latest-events-module-include-events-from-sub-categories-has-no-effect#reply-215681
=> Fix include sub cat support for latest events module

component/site/libraries/dbmodel.php, modules/mod_jevents_legend/tmpl/alternative/legend.php, modules/mod_jevents_legend/tmpl/default/legend.php, modules/mod_jevents_legend/tmpl/ext/legend.php, modules/mod_jevents_legend/tmpl/flat/legend.php
Result of ArrayHelper::toInteger was not being assigned.
=> Fix use of ArrayHelper

component/admin/views/defaults/tmpl/overview.php, component/admin/views/icals/tmpl/overview.php
Added coloured support to state icon for calendars and custom layouts.
=> Added coloured support to state icon for calendars and custom layouts.

component/site/controllers/icalrepeat.php
Resolves issue:
https://www.jevents.net/discussions/problem-with-permissions
=> Mirror Event Edit Permissions for Event Repeats.

package/install.php
As we now use namespacing and FileSystem we need to jump to 3.9 min.
=> Bump Joomla! Required version to 3.9

component/site/views/default/helpers/defaulteventmanagementdialog.php, component/site/views/default/helpers/defaultvieweventrowadmin.php
This fixes showing edit repeat options on J4, but it's a patch and not the original issue. $row->count() is returning 999.
=> Fix isRepeat
